# Generated by Django 4.1.2 on 2022-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_song_song_artiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=3500),
        ),
    ]
